version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./.build/web/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - node
  php-fpm:
    build: ./.build/php-fpm
    volumes:
      - ./:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
      - composer
  composer:
    image: composer:latest
    volumes:
      - ./:/app
    command: composer update
  migrations:
    build: ./.build/php-cli
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - composer
    working_dir: /app
    command: ./vendor/bin/doctrine-migrations migrate --no-interaction --configuration=migrations.php --db-configuration=migrations-db.php
  mysql:
    image: mysql:5
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      TZ: "Europe/London"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "Password1!"
      MYSQL_USER: "lamp"
      MYSQL_PASSWORD: "Password1!"
      MYSQL_DATABASE: "lamp"
  node:
    image: node:lts-alpine
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm install --unsafe-perm
volumes:
  mysql:
